### ISSUE TITLE
SIMPLIFY - dry css

### ISSUE THREAD

**Issue by franfranfranfran** [sanjayzope/prj-rev-bwfs-dasmoto#1]
https://github.com/sanjayzope/prj-rev-bwfs-dasmoto/blob/master/DevProject/resources/css/index.css#L3
https://github.com/sanjayzope/prj-rev-bwfs-dasmoto/blob/master/DevProject/resources/css/index.css#L11
etc...

try to keep in mind dry principles when setting your css. are there any elements on the page that should not receive the helvetica font-family? can you set this styling just once for the entire page?

**Comment by sanjayzope** [comment]
Fixed by moving font to body tag since entire page uses that font and follow DRY principle
