### ISSUE TITLE
IMPORTANT - img alt attribute

### ISSUE THREAD

**Issue by franfranfranfran** [sanjayzope/prj-rev-bwfs-dasmoto#3]
https://github.com/sanjayzope/prj-rev-bwfs-dasmoto/blob/master/DevProject/index.html#L13
etc...

make sure to use an alt attribute for each img element to ensure that a wider variety of users have access to the information contained in those images. more info can be found here - https://www.w3schools.com/tags/att_img_alt.asp

**Comment by sanjayzope** [comment]
fixed
