### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [sanjayzope/prj-rev-bwfs-dasmoto#5]
**GRADE**: Meets Expectations

**SUMMARY**: Good work on this project! With a couple small tweaks with font-family, the site itself will be looking great and you did an excellent job keeping both the project folder and the code neat, organized, and readable. Great job making use of relative file paths to link to your local images as well!

Behind the scenes in the html, make sure to use alt attributes with your img elements. These will ensure that a wider variety of users have access to the information being presented by those images. In your css, try to always keep in mind DRY principles. Avoid repeating lines of styling for similarly styled elements wherever possible.

From here, you’re in a great place to spruce up the page beyond what the spec shows. You could try any number of things.  One possibility is to put the item text in each section up next to the image. How might we accomplish this? Check here for more info - https://developer.mozilla.org/en-US/docs/Web/CSS/float?v=example

Keep up the good work!

**Comment by sanjayzope** [comment]
Cool. Thanks for prompt review. Fixed all issues.
